[package]
name = "clients_db"
version = "0.1.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"

[dependencies]
fo_save_format = { git = "https://github.com/qthree/fo_save_format.git" }
tnf_common = { path = "../common" }
arrayvec = "0.4.10"
itertools = "0.8.0"
