[host]
#web_tls = { full_chain = "", key = "" }
web = { domain = "localhost", port = 8000}
files = { domain = "127.0.0.1", port = 8001}

[paths]
save_clients = "../../FO4RP/save/clients/"
proto_items = "../../FO4RP/proto/items/items.lst"
working_dir = "../web"
game_client = "../../CL4RP"
palette = "../../test_assets/COLOR.PAL"
private = ["../../FO4RP/logs", "../../FO4RP/dumps", "../../FO4RP/save"]

[discord]
main_guild_id = 540139771880800266
oauth2 = { client_id = "", secret = ""}
bot = { token = "" }

[discord.roles]
admin = "Adm"
developer = "Dev"
gamemaster = "GM"
player = "Игрок"

[session]
#cookie_key = ""
